version: '3.0'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - './:/opt/cboard-api/'
    ports:
      - '8088:10010'
    environment:
      - AZURE_STORAGE_CONNECTION_STRING
      - FACEBOOK_APP_ID=1234567890
      - FACEBOOK_APP_SECRET
      - FACEBOOK_CALLBACK_URL
      - GCLOUD_PROJECT
      - GOOGLE_APP_ID=1234567890
      - GOOGLE_APP_SECRET
      - GOOGLE_APPLICATION_CREDENTIALS
      - GOOGLE_CALLBACK_URL=http://localhost:8080/
      - JWT_SECRET="1234567890qwertyuiop"
      - JWT_PUBLIC_KEY
      - MONGO_URL=mongodb://db/cboard-api
      - REACT_APP_DEV_API_URL
      - SENDGRID_API_KEY
      - DD_ENV="dev"
      - DD_SERVICE="cboard-api"
      - DD_VERSION="1.3.1"
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - CBOARD_CONTAINER_NAME
      - USE_CLOUD_SERVICE
      - CBOARD_CDN_DISTRIBUTION_ID
      - CBOARD_CDN_DIRECTORY
    command: 'npm run dev'
  db:
    image: mongo
    ports:
      - '27017:27017'
